In [ ]:
import numpy as np

In [15]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [18]:
a=np.ones(10)*5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [19]:
a=np.arange(10,51)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [20]:
a=np.arange(10,51,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [83]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
a=np.random.rand()
print(a)

0.3940944061298447


In [33]:
a=np.random.randn(25)
print(a)

[-0.32877044 -2.05587566  1.17191524 -0.36084827 -0.69713253  0.29262964
 -0.83206267  1.09451298 -0.39150618 -0.08543399 -0.49995957  1.4629231
 -0.7795172   0.07887924  1.42693232  0.60518407  1.19927611 -1.12314933
  0.07457243 -1.47949912 -0.20720462  0.9398192   0.06756189 -0.31474846
 -1.19694702]


In [67]:
a=np.arange(1,101)/100
b=a.reshape(10,10)
print(b)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [165]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [166]:
print(mat[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [167]:
print(mat[3,4])

20


In [168]:
print(mat[:3,1])

[ 2  7 12]


In [169]:
print(mat[4])

[21 22 23 24 25]


In [170]:
print(mat[3:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [171]:
print(np.sum(mat))

325


In [172]:
print(mat.std())

7.211102550927978


In [173]:
print(mat.sum(axis=0))

[55 60 65 70 75]
